// Text of the terminal scenes. The output of `npm run vo` comes from a real run (only long lines shortened with "…");
// post_render.sh and post_social.py follow the output format of the scripts, numbers and names are example values.
import type { Item } from "./Terminal";

export const VO_TAKE = "take-20261008-153933-1.wav";

export const voScript: Item[] = [
  { k: "cmd", lines: [`npm run vo -- recordings/${VO_TAKE}`] },
  { k: "out", text: "1/4 Assembling pieces", cls: "head", wait: 14 },
  { k: "out", text: `  Piece 1: ${VO_TAKE} 0–10856 ms, +0.0 dB → starts in the result at 0 ms`, cls: "dim" },
  { k: "out", text: "2/4 Mastering", cls: "head", wait: 10 },
  { k: "out", text: "Mastered [neutral]: … two-channel file -14.00 LUFS, peak -1.76 dBTP, LRA 4.3 | limiter …", cls: "dim", wait: 12 },
  { k: "out", text: "3/4 Aligning (1 model)", cls: "head", wait: 10 },
  { k: "out", text: "  transcribing: large-v3-turbo", cls: "dim", wait: 12 },
  { k: "out", text: "vo.wav: 10856 ms, 6 speech segments: [[780, 1740], [2155, 2780], [3475, 4880], …]", cls: "dim", wait: 20 },
  { k: "out", text: "Models: large-v3-turbo", cls: "dim", wait: 4 },
  { k: "out", text: "Key           Start ms  Word         Pause    Spread     P   large-v3-turbo", cls: "key", wait: 6 },
  { k: "out", text: "thisIs             780  this         ●             0  0.54              –", wait: 5 },
  { k: "out", text: "yourHook          1200  your                       0  0.98           1200", wait: 5 },
  { k: "out", text: "hello             2160  hello        ●             0  0.78           2000", wait: 5 },
  { k: "out", text: "look              3480  look         ●             0  0.81           3140", wait: 5 },
  { k: "out", text: "numbers           4160  numbers                    0  1.00           4160", wait: 5 },
  { k: "out", text: "im                5840  im           ●             0  1.00           5360", wait: 5 },
  { k: "out", text: "yourName          6060  your                       0  1.00           6060", wait: 5 },
  { k: "out", text: "thanks            7030  thanks       ●             0  0.98           6960", wait: 5 },
  { k: "out", text: "4/4 Writing", cls: "head", wait: 14 },
  { k: "out", text: "Done: public/vo.wav and src/timing.ts written.", cls: "ok", wait: 12 },
  { k: "gap", frames: 40 },
  { k: "clear" },
  { k: "cmd", lines: ["tail -14 src/timing.ts"], cps: 22 },
  { k: "out", text: "export const VO = {", ts: true, wait: 10 },
  { k: "out", text: '  /** Audio file under public/ ("" = no voiceover) */', ts: true, wait: 1 },
  { k: "out", text: '  file: "vo.wav",', ts: true, wait: 1 },
  { k: "out", text: "  /** Length of the video in ms (last word ends at 8775 ms, then the tail) */", ts: true, wait: 1 },
  { k: "out", text: "  endMs: 9400,", ts: true, wait: 1 },
  { k: "out", text: "  w: {", ts: true, wait: 1 },
  { k: "out", text: '    // Scene 1: "this is your hook, hello"', ts: true, wait: 1 },
  { k: "out", text: "    thisIs: 780, yourHook: 1200, hello: 2160,", ts: true, wait: 1 },
  { k: "out", text: '    // Scene 2: "look at these numbers"', ts: true, wait: 1 },
  { k: "out", text: "    look: 3480, numbers: 4160,", ts: true, wait: 1 },
  { k: "out", text: `    // Scene 3: "I'm Your Name, thanks for watching"`, ts: true, wait: 1 },
  { k: "out", text: "    im: 5840, yourName: 6060, thanks: 7030,", ts: true, wait: 1 },
  { k: "out", text: "  },", ts: true, wait: 1 },
  { k: "out", text: "};", ts: true, wait: 1 },
  { k: "prompt" },
];

export const renderScript: Item[] = [
  { k: "cmd", lines: ["EDIT_HOST=edit-mac edit-tools/post_render.sh \\", "my-video Demo my-video 60,150,240"], cps: 26 },
  { k: "gap", frames: 44 },
  { k: "out", text: "with-music: mix -12.8 LUFS / -0.4 dBTP, gain -1.2 dB -> final -14.0 LUFS / -1.6 dBTP, 14M", cls: "ok", wait: 4 },
  { k: "out", text: "without-music: mix -15.2 LUFS / -3.1 dBTP, gain 0 dB -> final -15.2 LUFS / -3.1 dBTP, 13M", cls: "ok", wait: 18 },
  { k: "out", text: "h264,High,1080,1920,30/1,yuv420p,bt709", cls: "dim", wait: 18 },
  { k: "out", text: "Done: edit-mac:~/my-video/out/post-2026-10-08/", cls: "head", wait: 12 },
  { k: "gap", frames: 26 },
  { k: "cmd", lines: ["ssh edit-mac ls -1 my-video/out/post-2026-10-08"], cps: 28 },
  { k: "out", text: "audio-with-music.wav", wait: 14 },
  { k: "out", text: "audio-without-music.wav", wait: 2 },
  { k: "out", text: "cover-frame-150.png", wait: 2 },
  { k: "out", text: "cover-frame-240.png", wait: 2 },
  { k: "out", text: "cover-frame-60.png", wait: 2 },
  { k: "out", text: "my-video_1080x1920_with-music.mp4", cls: "key", wait: 2 },
  { k: "out", text: "my-video_1080x1920_without-music.mp4", cls: "key", wait: 2 },
  { k: "out", text: "video.mp4", wait: 2 },
  { k: "prompt" },
];

export const postScript: Item[] = [
  { k: "cmd", lines: ["python3 edit-tools/post_social.py tiktok out/my-video.mp4 \\", "--caption-file caption-tiktok.txt --dry-run"], cps: 28 },
  { k: "out", text: "Dry run: no upload, the call contains a placeholder URL.", cls: "dim", wait: 16 },
  { k: "out", text: "TikTok: create DRAFT (is_draft)", cls: "head", wait: 14 },
  { k: "out", text: "  {", wait: 6 },
  { k: "out", text: '    "slug": "ZERNIO_MCP_POSTS_CREATE",', wait: 3 },
  { k: "out", text: '    "arguments": {', wait: 3 },
  { k: "out", text: '      "platform": "tiktok",', wait: 3 },
  { k: "out", text: '      "content": "This is how a short video is made #remotion #shortvideo",', wait: 3 },
  { k: "out", text: '      "account_id": "<account-id>",', wait: 3 },
  { k: "out", text: '      "media_urls": "https://example.invalid/public-url-comes-after-the-upload.mp4",', wait: 3 },
  { k: "out", text: '      "is_draft": true', cls: "key", wait: 3 },
  { k: "out", text: "    }", wait: 3 },
  { k: "out", text: "  }", wait: 3 },
  { k: "out", text: "Dry run: nothing was created or published.", cls: "ok", wait: 14 },
  { k: "gap", frames: 26 },
  { k: "out", text: "", wait: 2 },
  { k: "out", text: "# Order: have a human approve the caption → create the draft", cls: "dim", wait: 8 },
  { k: "out", text: "# → second approval → only then --publish", cls: "dim", wait: 2 },
  { k: "prompt" },
];
