// Text der Terminal-Szenen. Die Ausgabe von `npm run vo` stammt aus einem echten Lauf (nur lange Zeilen mit „…“ gekürzt);
// post_render.sh und post_social.py folgen dem Ausgabeformat der Skripte, Zahlen und Namen sind Beispielwerte.
import type { Item } from "./Terminal";

export const VO_TAKE = "take-20261008-153933-1.wav";

export const voScript: Item[] = [
  { k: "cmd", lines: [`npm run vo -- recordings/${VO_TAKE}`] },
  { k: "out", text: "1/4 Stücke zusammensetzen", cls: "head", wait: 14 },
  { k: "out", text: `  Stück 1: ${VO_TAKE} 0–10856 ms, +0.0 dB → beginnt im Ergebnis bei 0 ms`, cls: "dim" },
  { k: "out", text: "2/4 Aufbereiten", cls: "head", wait: 10 },
  { k: "out", text: "Aufbereitet [neutral]: … Zweikanal-Datei -14.00 LUFS, Spitze -1.76 dBTP, LRA 4.3 | Begrenzer …", cls: "dim", wait: 12 },
  { k: "out", text: "3/4 Ausrichten (1 Modell)", cls: "head", wait: 10 },
  { k: "out", text: "  hört ab: large-v3-turbo", cls: "dim", wait: 12 },
  { k: "out", text: "vo.wav: 10856 ms, 6 Sprechabschnitte: [[780, 1740], [2155, 2780], [3475, 4880], …]", cls: "dim", wait: 20 },
  { k: "out", text: "Modelle: large-v3-turbo", cls: "dim", wait: 4 },
  { k: "out", text: "Schlüssel    Beginn ms  Wort         Pause  Streuung     P   large-v3-turbo", cls: "key", wait: 6 },
  { k: "out", text: "thisIs             780  this         ●             0  0.54              –", wait: 5 },
  { k: "out", text: "yourHook          1200  your                       0  0.98           1200", wait: 5 },
  { k: "out", text: "hello             2160  hello        ●             0  0.78           2000", wait: 5 },
  { k: "out", text: "look              3480  look         ●             0  0.81           3140", wait: 5 },
  { k: "out", text: "numbers           4160  numbers                    0  1.00           4160", wait: 5 },
  { k: "out", text: "im                5840  im           ●             0  1.00           5360", wait: 5 },
  { k: "out", text: "yourName          6060  your                       0  1.00           6060", wait: 5 },
  { k: "out", text: "thanks            7030  thanks       ●             0  0.98           6960", wait: 5 },
  { k: "out", text: "4/4 Schreiben", cls: "head", wait: 14 },
  { k: "out", text: "Fertig: public/vo.wav und src/timing.ts geschrieben.", cls: "ok", wait: 12 },
  { k: "gap", frames: 40 },
  { k: "clear" },
  { k: "cmd", lines: ["tail -14 src/timing.ts"], cps: 22 },
  { k: "out", text: "export const VO = {", ts: true, wait: 10 },
  { k: "out", text: '  /** Audiodatei unter public/ ("" = kein Voiceover) */', ts: true, wait: 1 },
  { k: "out", text: '  file: "vo.wav",', ts: true, wait: 1 },
  { k: "out", text: "  /** Länge des Videos in ms (letztes Wort endet bei 8775 ms, danach Ausklang) */", ts: true, wait: 1 },
  { k: "out", text: "  endMs: 9400,", ts: true, wait: 1 },
  { k: "out", text: "  w: {", ts: true, wait: 1 },
  { k: "out", text: '    // Szene 1: "this is your hook, hello"', ts: true, wait: 1 },
  { k: "out", text: "    thisIs: 780, yourHook: 1200, hello: 2160,", ts: true, wait: 1 },
  { k: "out", text: '    // Szene 2: "look at these numbers"', ts: true, wait: 1 },
  { k: "out", text: "    look: 3480, numbers: 4160,", ts: true, wait: 1 },
  { k: "out", text: `    // Szene 3: "I'm Your Name, thanks for watching"`, ts: true, wait: 1 },
  { k: "out", text: "    im: 5840, yourName: 6060, thanks: 7030,", ts: true, wait: 1 },
  { k: "out", text: "  },", ts: true, wait: 1 },
  { k: "out", text: "};", ts: true, wait: 1 },
  { k: "prompt" },
];

export const renderScript: Item[] = [
  { k: "cmd", lines: ["EDIT_HOST=schnitt-mac edit-tools/post_render.sh \\", "mein-video Demo mein-video 60,150,240"], cps: 26 },
  { k: "gap", frames: 44 },
  { k: "out", text: "mit-Musik: Mix -12.8 LUFS / -0.4 dBTP, Pegel -1.2 dB -> fertig -14.0 LUFS / -1.6 dBTP, 14M", cls: "ok", wait: 4 },
  { k: "out", text: "ohne-Musik: Mix -15.2 LUFS / -3.1 dBTP, Pegel 0 dB -> fertig -15.2 LUFS / -3.1 dBTP, 13M", cls: "ok", wait: 18 },
  { k: "out", text: "h264,High,1080,1920,30/1,yuv420p,bt709", cls: "dim", wait: 18 },
  { k: "out", text: "Fertig: schnitt-mac:~/mein-video/out/post-2026-10-08/", cls: "head", wait: 12 },
  { k: "gap", frames: 26 },
  { k: "cmd", lines: ["ssh schnitt-mac ls -1 mein-video/out/post-2026-10-08"], cps: 28 },
  { k: "out", text: "bild.mp4", wait: 14 },
  { k: "out", text: "cover-bild-150.png", wait: 2 },
  { k: "out", text: "cover-bild-240.png", wait: 2 },
  { k: "out", text: "cover-bild-60.png", wait: 2 },
  { k: "out", text: "mein-video_1080x1920_mit-Musik.mp4", cls: "key", wait: 2 },
  { k: "out", text: "mein-video_1080x1920_ohne-Musik.mp4", cls: "key", wait: 2 },
  { k: "out", text: "ton-mit-musik.wav", wait: 2 },
  { k: "out", text: "ton-ohne-musik.wav", wait: 2 },
  { k: "prompt" },
];

export const postScript: Item[] = [
  { k: "cmd", lines: ["python3 edit-tools/post_social.py tiktok out/mein-video.mp4 \\", "--caption-file beschreibung-tiktok.txt --dry-run"], cps: 28 },
  { k: "out", text: "Trockenlauf: kein Upload, im Aufruf steht eine Platzhalter-URL.", cls: "dim", wait: 16 },
  { k: "out", text: "TikTok: ENTWURF anlegen (is_draft)", cls: "head", wait: 14 },
  { k: "out", text: "  {", wait: 6 },
  { k: "out", text: '    "slug": "ZERNIO_MCP_POSTS_CREATE",', wait: 3 },
  { k: "out", text: '    "arguments": {', wait: 3 },
  { k: "out", text: '      "platform": "tiktok",', wait: 3 },
  { k: "out", text: '      "content": "So entsteht ein Kurzvideo #remotion #kurzvideo",', wait: 3 },
  { k: "out", text: '      "account_id": "<konto-id>",', wait: 3 },
  { k: "out", text: '      "media_urls": "https://example.invalid/oeffentliche-url-kommt-nach-dem-upload.mp4",', wait: 3 },
  { k: "out", text: '      "is_draft": true', cls: "key", wait: 3 },
  { k: "out", text: "    }", wait: 3 },
  { k: "out", text: "  }", wait: 3 },
  { k: "out", text: "Trockenlauf: nichts wurde angelegt oder veröffentlicht.", cls: "ok", wait: 14 },
  { k: "gap", frames: 26 },
  { k: "out", text: "", wait: 2 },
  { k: "out", text: "# Reihenfolge: Beschreibung von einem Menschen freigeben lassen → Entwurf anlegen", cls: "dim", wait: 8 },
  { k: "out", text: "# → zweite Freigabe → erst dann --publish", cls: "dim", wait: 2 },
  { k: "prompt" },
];
