// Demo (9 s, 9:16): three short scenes, timed to word times – the same building blocks as in a real short video, just without content of its own.
// All times come from src/timing.ts (word times) – there are no fixed times here, picture and sound hang on the same constants.
//
//  1  "this is your hook, hello"        white card + inset clip (slow zoom), three lines of text, the script-font word sits slightly over the inset
//  2  "look at these numbers"           green number that keeps rising until the cut, plus a split-flap counter
//  3  "I'm Your Name, thanks for watching"  name above a second inset, squiggle arrow from the name to the clip, line of text below
import React from "react";
import { AbsoluteFill, Audio, Easing, interpolate, OffthreadVideo, Sequence, spring, staticFile, useCurrentFrame, useVideoConfig } from "remotion";
import { z } from "zod";
import { FONTS } from "./lib/fonts";
import { Word, Words } from "./lib/words";
import { Cue, SfxTrack, SOUNDS } from "./lib/sfx";
import { SafeZoneGuide } from "./lib/safezone";
import { VO } from "./timing";

/** Milliseconds in the voiceover → frames (30 fps). */
export const f = (ms: number) => Math.round(ms * 0.03);

/** Word times of the voiceover in ms – from src/timing.ts. */
const w = VO.w;
/** Scene boundaries in ms. Scene i runs from CUTS[i] to CUTS[i+1]. */
const CUTS = [0, w.look, w.im, VO.endMs];
const start = (i: number) => f(CUTS[i]);
const len = (i: number) => f(CUTS[i + 1]) - f(CUTS[i]);
export const DEMO_FRAMES = f(CUTS[3]);

const slotSchema = z.object({ label: z.string(), clip: z.string(), startSec: z.number().min(0) });

export const demoSchema = z.object({
  /** Audio file under public/. Empty = the file from src/timing.ts (VO.file, generated by Voice Studio); if that is empty too, there is no voiceover.
   *  The cuts belong to the word times in src/timing.ts – a different recording needs a new timing.ts (npm run vo). */
  voiceover: z.string(),
  voVolume: z.number().min(0).max(1),
  /** Music under public/ (empty = none). */
  music: z.string(),
  musicVolume: z.number().min(0).max(1),
  /** Volume of all sound effects together (0 = off, 1 = values from SFX_CUES). At 1.3 the effects are about as loud as music at 0.15. */
  sfxVolume: z.number().min(0).max(2),
  /** Value that the green number reaches exactly at the cut to scene 3 – it keeps rising until then. */
  counterTo: z.number().min(0),
  /** The two insets (scene 1 and 3). clip = file name under public/ (e.g. "clip.mp4"); empty = gray placeholder. */
  slots: z.array(slotSchema),
  /** true = tints the safe zones for Instagram/TikTok (lib/safezone.tsx). Only for checking, off before rendering. */
  safeZone: z.boolean(),
});
export type DemoProps = z.infer<typeof demoSchema>;
type Slot = z.infer<typeof slotSchema>;

export const demoDefaults: DemoProps = {
  voiceover: "",
  voVolume: 1,
  music: "",
  musicVolume: 0.15,
  sfxVolume: 1.3,
  counterTo: 1000000,
  slots: [
    { label: "your clip", clip: "", startSec: 0 },
    { label: "your clip", clip: "", startSec: 0 },
  ],
  safeZone: false,
};

// ------------------------------------------------------------ Building blocks
const NONE: Slot = { label: "", clip: "", startSec: 0 };

/** Video or gray placeholder with a label. */
const Media: React.FC<{ slot: Slot; hue: number }> = ({ slot, hue }) =>
  slot.clip ? (
    <OffthreadVideo src={staticFile(slot.clip)} muted trimBefore={Math.round(slot.startSec * 30)} style={{ width: "100%", height: "100%", objectFit: "cover" }} />
  ) : (
    <AbsoluteFill
      style={{
        background: `linear-gradient(160deg, hsl(${hue} 15% 86%), hsl(${hue} 18% 74%))`,
        justifyContent: "center",
        alignItems: "center",
        color: "rgba(0,0,0,0.35)",
        fontSize: 34,
        letterSpacing: "0.18em",
        textAlign: "center",
        padding: 40,
        lineHeight: 1.5,
        ...FONTS.sansLight,
      }}
    >
      {slot.label}
    </AbsoluteFill>
  );

/** Width of the inset in % of the frame width (16:9, so height = width · 9/16). */
const INSET_WIDTH = 86;

/** Rounded 16:9 inset on a white card. */
const Inset: React.FC<{ slot: Slot; hue: number; top?: number; radius?: number; zoom?: { to: number; origin: string; frames: number } }> = ({ slot, hue, top = 37, radius = 28, zoom }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const sp = spring({ frame, fps, config: { damping: 14, stiffness: 160 } });
  // zoom: the clip grows evenly to `to` over `frames` frames, around the point `origin` (in % of the clip)
  const z = zoom ? interpolate(frame, [0, zoom.frames], [1, zoom.to], { extrapolateRight: "clamp" }) : 1;
  return (
    <div
      style={{
        position: "absolute",
        left: `${(100 - INSET_WIDTH) / 2}%`,
        top: `${top}%`,
        width: `${INSET_WIDTH}%`,
        aspectRatio: "16 / 9",
        transform: `scale(${interpolate(sp, [0, 1], [0.92, 1])})`,
        opacity: interpolate(frame, [0, 4], [0, 1], { extrapolateRight: "clamp" }),
        boxShadow: "0 10px 30px rgba(0,0,0,0.12)",
        borderRadius: radius,
        overflow: "hidden",
        background: "#dfe3ea",
      }}
    >
      {zoom ? (
        <AbsoluteFill style={{ transform: `scale(${z})`, transformOrigin: zoom.origin }}>
          <Media slot={slot} hue={hue} />
        </AbsoluteFill>
      ) : (
        <Media slot={slot} hue={hue} />
      )}
    </div>
  );
};

/** All word texts pop in 100 ms (3 frames) before their spoken word. That is how long the fade-in takes –
 *  so they are fully visible exactly at the start of the word instead of 1–3 frames after it. If a scene starts exactly
 *  on the word ("look at", "I'm"), the onset becomes negative: the text is then fully visible already in the first frame of the scene. */
const TEXT_LEAD_MS = 100;

/** Words with onset time in ms in the voiceover (absolute) → frames relative to the scene. */
const rel = (sceneIdx: number, ws: (Omit<Word, "at"> & { ms: number })[]): Word[] => ws.map(({ ms, ...w }) => ({ ...w, at: f(ms - TEXT_LEAD_MS) - start(sceneIdx) }));

const RED = "#e1251b";
const GREEN = "#12b76a";
const GREEN_DARK = "#0a8f50";

// ------------------------------------------------------------ Scenes
const S1: React.FC<{ slot: Slot }> = ({ slot }) => (
  <AbsoluteFill style={{ background: "#fff" }}>
    <Inset slot={slot} hue={210} top={44} zoom={{ to: 1.12, origin: "50% 50%", frames: len(0) }} />
    <Words
      color="#000"
      words={rel(0, [
        { ms: w.thisIs, text: "this is", font: "sansLight", size: 76, x: 28, y: 11 },
        { ms: w.yourHook, text: "your hook", font: "sans", size: 176, x: 50, y: 17.5 },
        // the script-font word spans from the left to the right edge of the frame and sits slightly over the inset at the bottom
        { ms: w.hello, text: "hello", font: "script", size: 520, x: 48.5, y: 38.5, weight: 700, color: RED },
      ])}
    />
  </AbsoluteFill>
);

/** Frame (within the scene) from which the number counts: exactly at the word "numbers". */
const COUNT_AT = f(w.numbers) - start(1);

/** Green number that keeps rising until the cut (accelerating) and does not land on a round end value. */
const Counter: React.FC<{ counterTo: number }> = ({ counterTo }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const local = frame - COUNT_AT;
  if (local < 0) return null;
  const count = counterTo * Math.pow(Math.min(1, local / (len(1) - COUNT_AT)), 2.3);
  const pop = spring({ frame: local, fps, config: { damping: 12, stiffness: 170, mass: 0.8 } });
  const arrowBob = Math.sin(local / 4) * 7;
  return (
    <div style={{ position: "absolute", left: 0, right: 0, top: 800, display: "flex", justifyContent: "center", alignItems: "center", gap: 24, transform: `scale(${interpolate(pop, [0, 1], [0.8, 1])})`, opacity: interpolate(local, [0, 4], [0, 1], { extrapolateRight: "clamp" }) }}>
      <div style={{ color: GREEN, fontSize: 168, lineHeight: 1, ...FONTS.sans, fontWeight: 900, letterSpacing: "-0.04em", fontVariantNumeric: "tabular-nums", textShadow: "0 6px 30px rgba(18,183,106,0.28)" }}>{Math.round(count).toLocaleString("en-US")}</div>
      <div style={{ color: GREEN, fontSize: 90, lineHeight: 1, transform: `translateY(${-arrowBob}px)` }}>▲</div>
    </div>
  );
};

const S2: React.FC<{ counterTo: number }> = ({ counterTo }) => (
  <AbsoluteFill style={{ background: "#fff" }}>
    <Counter counterTo={counterTo} />
    <Words
      color="#000"
      words={rel(1, [
        { ms: w.look, text: "look at these", font: "sansLight", size: 84, x: 50, y: 31 },
        { ms: w.numbers, text: "views", font: "serifItalic", size: 130, x: 50, y: 60, color: GREEN_DARK },
      ])}
    />
  </AbsoluteFill>
);

/** Position of name and inset in scene 3 (% of the height) – the start and tip of the arrow follow from it. */
const NAME_Y = 22;
const INSET3_TOP = 38;
/** Middle of the inset in pixels (1080 × 1920): the arrow points there. */
const INSET_MID_Y = (INSET3_TOP / 100) * 1920 + (1080 * (INSET_WIDTH / 100) * 9) / 16 / 2;

/** Squiggle arrow from the name to the middle of the inset, as if drawn by hand: a line with a loop that draws itself from SQUIGGLE_AT
 *  over SQUIGGLE_FRAMES frames, then the two strokes of the arrowhead. The start (SX, SY) lies below the end of the name, the tip (EX, EY) in the middle of the inset.
 *  The curve is built relative to start and tip, so if you move one of the two points, the arrow still runs there. Coordinates in pixels. */
const SX = 880;
const SY = (NAME_Y / 100) * 1920 + 110;
const EX = 650;
const EY = INSET_MID_Y;
const SQUIGGLE = `M ${SX} ${SY} C ${SX + 85} ${SY + 2} ${SX + 129} ${SY + 60} ${SX + 97} ${SY + 116} C ${SX + 71} ${SY + 162} ${SX + 1} ${SY + 156} ${SX + 1} ${SY + 111} C ${SX + 1} ${SY + 66} ${SX + 71} ${SY + 62} ${SX + 85} ${SY + 128} C ${SX + 99} ${SY + 198} ${EX + 182} ${EY} ${EX} ${EY}`;
const SQUIGGLE_HEAD = [`M ${EX} ${EY} L ${EX + 34} ${EY - 21}`, `M ${EX} ${EY} L ${EX + 30} ${EY + 25}`];
const SQUIGGLE_AT = f(w.yourName + 60) - start(2);
const SQUIGGLE_FRAMES = 12;
const Squiggle: React.FC = () => {
  const frame = useCurrentFrame();
  if (frame < SQUIGGLE_AT) return null;
  const line = interpolate(frame, [SQUIGGLE_AT, SQUIGGLE_AT + SQUIGGLE_FRAMES], [0, 1], { extrapolateRight: "clamp", easing: Easing.inOut(Easing.cubic) });
  const head = interpolate(frame, [SQUIGGLE_AT + SQUIGGLE_FRAMES, SQUIGGLE_AT + SQUIGGLE_FRAMES + 3], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  // pathLength 1 + dash pattern 1: strokeDashoffset 1 = nothing drawn, 0 = whole line
  const pen = { fill: "none", stroke: RED, strokeWidth: 9, strokeLinecap: "round" as const, strokeLinejoin: "round" as const, pathLength: 1, strokeDasharray: 1 };
  return (
    <svg viewBox="0 0 1080 1920" style={{ position: "absolute", inset: 0, width: "100%", height: "100%" }}>
      <path d={SQUIGGLE} {...pen} strokeDashoffset={1 - line} />
      {head > 0 ? SQUIGGLE_HEAD.map((d) => <path key={d} d={d} {...pen} strokeDashoffset={1 - head} />) : null}
    </svg>
  );
};

/** Ending: "I'm" + name at the top, below it the inset with a slight zoom, the squiggle arrow points from the name into the clip, a line of text below the inset. */
const S3: React.FC<{ slot: Slot }> = ({ slot }) => {
  const frame = useCurrentFrame();
  const frames = len(2);
  const fade = interpolate(frame, [frames - 8, frames], [1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  return (
    <AbsoluteFill style={{ background: "#fff" }}>
      <AbsoluteFill style={{ opacity: fade }}>
        <Inset slot={slot} hue={210} top={INSET3_TOP} zoom={{ to: 1.12, origin: "50% 50%", frames }} />
        <Words
          color="#000"
          words={rel(2, [
            { ms: w.im, text: "I'm", font: "sansLight", size: 84, x: 22, y: NAME_Y - 7.5 },
            { ms: w.yourName, text: "Your Name", font: "sans", size: 160, x: 52, y: NAME_Y },
            { ms: w.thanks, text: "thanks for watching", font: "sansLight", size: 84, x: 50, y: 75 },
          ])}
        />
        <Squiggle />
      </AbsoluteFill>
    </AbsoluteFill>
  );
};

// ------------------------------------------------------------ Composition
/** Sound effects. at = frame in the video on which the sound sits (for whooshes the loudest point); vol = volume 0–1.
 *  The frames hang on the same word times and animation values as the picture, so they move along with a new timing.ts.
 *  Level: the vol values give the ratio of the sounds to each other (drum and page stronger, keys and flaps quiet).
 *  How loud they are together is set by sfxVolume. The catalog with the files is in lib/sfx.tsx. */
/** One flap of the airport split-flap board in three slightly different pitches; FLAP_ORDER shuffles them so that no pattern is audible. */
const FLAPS = ["flapLo", "flap", "flapHi"] as const;
const FLAP_ORDER = [1, 0, 2, 0, 1, 2, 0];
const COUNT_TICKS = Math.floor((f(CUTS[2]) - 2 - f(w.numbers)) / 3) + 1;
/** Frame on which a word text pops in (TEXT_LEAD_MS before the spoken word). */
const pop = (ms: number) => Math.max(0, f(ms - TEXT_LEAD_MS));
/** The riser should end exactly on the cut into scene 3: its end lies (len − lead) after the point that sits on `at`. */
const RISER_AT = f(CUTS[2] - (SOUNDS.riser1.len - SOUNDS.riser1.lead));
const SFX_CUES: Cue[] = [
  // Scene 1: shutter when the clip pops in; a quiet key press for each line of text; a pencil stroke on the script-font word
  { at: start(0), s: "shutterSlr3", vol: 0.085, name: "Hook clip (shutter)" },
  { at: pop(w.thisIs), s: "key1", vol: 0.07, name: "this is (key)" },
  { at: pop(w.yourHook), s: "key2", vol: 0.075, name: "your hook (key)" },
  { at: pop(w.hello), s: "pencil1", vol: 0.04, name: "hello (pencil)" },
  // Scene 2: a page turns on the cut; one flap of the airport board every 3 frames, getting louder until the cut;
  // a reversed cymbal swells and ends exactly on the cut
  { at: start(1), s: "page1", vol: 0.12, name: "Cut to number (page turn)" },
  ...Array.from({ length: COUNT_TICKS }, (_, i): Cue => {
    const p = i / Math.max(1, COUNT_TICKS - 1);
    return { at: f(w.numbers) + i * 3, s: FLAPS[FLAP_ORDER[i % FLAP_ORDER.length]], vol: 0.02 + 0.03 * p, name: `Number ${i + 1}` };
  }),
  { at: RISER_AT, s: "riser1", vol: 0.06, name: "Riser before cut" },
  // Scene 3: drum on the first frame, shutter when the clip pops in; pencil while the squiggle arrow draws itself; key on the line of text
  { at: start(2), s: "tom1", vol: 0.13, name: "Cut to ending (drum)" },
  { at: start(2), s: "shutterInsta2", vol: 0.085, name: "Ending clip (shutter)" },
  { at: start(2) + SQUIGGLE_AT, s: "pencil1", vol: 0.042, name: "Squiggle arrow (pencil)" },
  { at: pop(w.thanks), s: "key3", vol: 0.075, name: "thanks for watching (key)" },
];

/** Music level per frame: it fades out over the last 18 frames. */
const musicGain = (frame: number) => interpolate(frame, [DEMO_FRAMES - 18, DEMO_FRAMES], [1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

export const Demo: React.FC<DemoProps> = ({ slots, voiceover, voVolume, music, musicVolume, sfxVolume, counterTo, safeZone }) => {
  const S = (i: number) => slots[i] ?? NONE;
  const voFile = voiceover || VO.file;
  const scene = (i: number, name: string, node: React.ReactNode) => (
    <Sequence key={i} from={start(i)} durationInFrames={len(i)} name={name}>
      {node}
    </Sequence>
  );
  return (
    <AbsoluteFill style={{ background: "#000" }}>
      {voFile ? <Audio src={staticFile(voFile)} volume={voVolume} /> : null}
      {music ? <Audio src={staticFile(music)} volume={(fr) => musicVolume * musicGain(fr)} /> : null}
      <SfxTrack cues={SFX_CUES} volume={sfxVolume} />
      {scene(0, "1 · Hook", <S1 slot={S(0)} />)}
      {scene(1, "2 · Number", <S2 counterTo={counterTo} />)}
      {scene(2, "3 · Ending", <S3 slot={S(1)} />)}
      {safeZone ? <SafeZoneGuide /> : null}
    </AbsoluteFill>
  );
};
